AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal SAM template for testing
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TestFunction
      Handler: app.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 60
    Metadata:
      SamResourceId: TestFunction
